### ISSUE TITLE
North Carolina AA Meme mode 

### ISSUE THREAD

**Issue by FCLC** [YourWaifuIsShip/Azur-Lane-Guides#22]
I was reading up on the exact way that the gold 410 mounted (confetti gun) and realized that its shell can and do effect aircraft. 

Equiping NC with dual PR radar, stag and twin 100MM AA. 

Even with NC at Lvl 108, I end up with ~600 FP before cats and  around 700 AA. 

since each shell splits into 22 units, and each unit deals he to planes (which are all light armour IIRC) we end up with each shell doing 20*1.45*1.30*1.10+FP(600), so ~650 per sub shell. since it fires 2 main shell, we then have 44 sub shells. (not to mention it fires 3 times with MGMT=3)

I've found that in boss nodes, it's enough to compensate for switching out a centaur(great with 4 fighter) for a ranger (who has no fighters). It also has the added bonus of adding a USS ship to help activate the Essex 4 USS skill. 

Will continue to try, but so far can full auto any 3* in 13-2 and 13-3 so long as you aren't on 0 ammo

**Comment by FCLC** [comment]
this might not be optimal from a damage perspective, but if you want a WW2 theme USS fleet that can clear 13-4, NC vestal and Enterprise do it remarkably well

**Comment by YourWaifuIsShip** [comment]
Oh I've already managed that quite handily with a different setup:
[Mob] Bataan Bunker Hill Langley Kai; Minneapolis San Juan Baltimore
[Boss] Washington North Carolina Georgia; PortKai Wichita San Diego 

Bunker Hill could easily be replaced by Enterprise, I didn't since I don't like her; and Washington _should_ be replaced by Alabama, but I didn't for the same reason.

The Sanshikigun remains a joke weapon by most intents and purposes, even if you end up killing planes (not a guarantee since the pellet count isn't that high and it's hard to aim it), you're certainly not killing surface enemies with it, and you're USS - why would you ever waste time with that thing when you're already rocking the best AA out there?
